apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-temperatura-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversor-temperatura
  template:
    metadata:
      labels:
        app: conversor-temperatura
    spec:
      containers:
        - name: conversor-temperatura
          image: fabricioveronez/conversao-temperatura:v1
          ports:
            - containerPort: 8080