apiVersion: v1
kind: Service
metadata:
  name: conversor-temperatura-service
spec:
  type: NodePort
  selector:
    app: conversor-temperatura
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000